SELECT b.TITLE, r. BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, 
DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS b
INNER JOIN USED_GOODS_REPLY AS r
ON b.board_id = r.board_id

WHERE b.CREATED_DATE LIKE '2022-10%'
ORDER BY  r.CREATED_DATE, b.TITLE;